/*
This file was generated by the Gradle 'init' task.
* For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12.1/userguide/building_java_projects.html in the Gradle documentation.
*/
plugins {
    application
    id("com.github.ben-manes.versions") version "0.52.0"
    id("com.dorongold.task-tree") version "4.0.1"
    kotlin("jvm") version "2.2.0"
}

repositories {
    mavenCentral()
}

dependencies {
//    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")
}

kotlin {
    jvmToolchain(11)
}

application {
    mainClass.set("com.nurflugel.gravitydoodle.DoodleFrame")
}
